package negocio;
// Generated 19-jun-2013 18:45:24 by Hibernate Tools 3.2.1.GA



/**
 * Alquiler generated by hbm2java
 */
public class Alquiler  implements java.io.Serializable {


     private Integer idAlquiler;
     private String idUsuario;
     private Integer idHorario;
     private String preciototal;
     private Integer idPista;

    public Alquiler() {
    }

    public Alquiler(String idUsuario, Integer idHorario, String preciototal, Integer idPista) {
       this.idUsuario = idUsuario;
       this.idHorario = idHorario;
       this.preciototal = preciototal;
       this.idPista = idPista;
    }
   
    public Integer getIdAlquiler() {
        return this.idAlquiler;
    }
    
    public void setIdAlquiler(Integer idAlquiler) {
        this.idAlquiler = idAlquiler;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public String getPreciototal() {
        return this.preciototal;
    }
    
    public void setPreciototal(String preciototal) {
        this.preciototal = preciototal;
    }
    public Integer getIdPista() {
        return this.idPista;
    }
    
    public void setIdPista(Integer idPista) {
        this.idPista = idPista;
    }




}


