package negocio;
// Generated 19-jun-2013 18:45:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private String diaSemana;
     private Date horaInicio;

    public Horario() {
    }

    public Horario(String diaSemana, Date horaInicio) {
       this.diaSemana = diaSemana;
       this.horaInicio = horaInicio;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }




}


