package negocio;
// Generated 19-jun-2013 18:45:24 by Hibernate Tools 3.2.1.GA



/**
 * Horariopista generated by hbm2java
 */
public class Horariopista  implements java.io.Serializable {


     private HorariopistaId id;
     private Boolean ocupada;

    public Horariopista() {
    }

	
    public Horariopista(HorariopistaId id) {
        this.id = id;
    }
    public Horariopista(HorariopistaId id, Boolean ocupada) {
       this.id = id;
       this.ocupada = ocupada;
    }
   
    public HorariopistaId getId() {
        return this.id;
    }
    
    public void setId(HorariopistaId id) {
        this.id = id;
    }
    public Boolean getOcupada() {
        return this.ocupada;
    }
    
    public void setOcupada(Boolean ocupada) {
        this.ocupada = ocupada;
    }




}


