package negocio;
// Generated 19-jun-2013 18:45:24 by Hibernate Tools 3.2.1.GA



/**
 * Pista generated by hbm2java
 */
public class Pista  implements java.io.Serializable {


     private Integer idPista;
     private String tipo;
     private String foto;
     private String precio;
     private Integer idInstalacion;

    public Pista() {
    }

    public Pista(String tipo, String foto, String precio, Integer idInstalacion) {
       this.tipo = tipo;
       this.foto = foto;
       this.precio = precio;
       this.idInstalacion = idInstalacion;
    }
   
    public Integer getIdPista() {
        return this.idPista;
    }
    
    public void setIdPista(Integer idPista) {
        this.idPista = idPista;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public Integer getIdInstalacion() {
        return this.idInstalacion;
    }
    
    public void setIdInstalacion(Integer idInstalacion) {
        this.idInstalacion = idInstalacion;
    }




}


