package negocio;
// Generated 19-jun-2013 19:02:41 by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String email;
     private String pass;
     private boolean administrador;

    public Usuario() {
    }

	
    public Usuario(boolean administrador) {
        this.administrador = administrador;
    }
    public Usuario(String nombre, String email, String pass, boolean administrador) {
       this.nombre = nombre;
       this.email = email;
       this.pass = pass;
       this.administrador = administrador;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public boolean isAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(boolean administrador) {
        this.administrador = administrador;
    }




}


